version: "3.9"
services:
  frontEnd:
    build:
      dockerfile: dockerfile
      context: ../front-end/
    image: front-end-technical_share:1.0
    container_name: front-technical_share
    restart: unless-stopped
    working_dir: /home/node/app/projeto
    networks:
      - frontend
    ports:
      - "3000:3000"
      - "8080:8080"
    stdin_open: true
    tty: true
    volumes:
      - ../front-end/:/home/node/app/projeto
      - ../front-end/package-lock.json:/home/node/app/package-lock.json
      - ../front-end/package.json:/home/node/app/package.json
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100

    depends_on:
      - "backEnd"
      - "mongodb"
  backEnd:
    build:
      dockerfile: dockerfile
      context: ../back-end/
    image: back-end-technical_share:1.0
    container_name: back-technical_share
    restart: unless-stopped
    working_dir: /home/node/api/src
    networks:
      - frontend
      - backend
    ports:
      - "3030:3030"
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - ../back-end/src:/home/node/api/src
      - ../back-end/public:/home/node/api/public
      - ../back-end/package-lock.json:/home/node/api/package-lock.json
      - ../back-end/package.json:/home/node/api/package.json
    depends_on:
      - "mongodb"
  mongodb:
    image: mongo:4.4.6
    container_name: mongo-technical_share
    ports:
      - "27017:27017"
    # volumes:
    #   - ../volume:/data/db
    networks: 
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge